# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'AmplifyCognitoAuthDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmplifyCognitoAuthDemo
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
